### ISSUE TITLE
你这个抄别人的。附上链接：https://github.com/saintwinkle/hexo-theme-scribble

### ISSUE THREAD

**Issue by blackshh** [stormzha/hexo-scribble#2]

**Comment by saintwinkle** [comment]
LICENSE 用 MIT 是是什么意思，我没懂您的意思，会按照你的要求来的，谢谢。

**Comment by smartbeng** [comment]
已经按照您的要求来了

**Comment by saintwinkle** [comment]
别改我的回答呀.. @smartbeng 

就是你现在的 LICENSE 是 Apache License 2.0，但是理论上 scribble 主题最终还是 fork 自这里：https://github.com/chloerei/scribble，原主题用了 MIT 协议，所以你要开源的话建议也沿用 MIT。其他就随便怎么用了。

**Comment by smartbeng** [comment]
哈哈，刚回复你搞错了，直接把你的给改了，好，你的意思我懂了。
